laurenx122/marea-furwell

- src/pages/Login/Login.css
- src/pages/Login/Login.js
- src/pages/Signup/Signup.css
- src/pages/Signup/Signup.js
> Login and Sign Up UI

- package-lock.json
- src/App.js
- src/pages/Clinic/ClinicHome.css
- src/pages/Login/Login.js
- src/pages/PetOwner/PetOwnerHome.css
- src/pages/PetOwner/PetOwnerHome.js
+ Pet Owner Page Added
- Pet Details
- Appointments
- Book an Appointments
> Pet Owner Landing Page

- package-lock.json
- src/pages/Signup/ClinicSubscribe.css
- src/pages/Signup/ClinicSubscribe.js
> clinicSubscribeInfo

- package-lock.json
- src/components/Navbar/Navbar.js
- src/components/Navbar/Navbar.module.css
- src/pages/Login/Login.js
Changes in:
- Navbar
- Navbar.module.css
- Login
Features:
Now can do admin login!
> Navbar FirstName Displayed

- src/components/Footer/Footer.js
- src/components/Navbar/Navbar.js
- src/components/Navbar/Navbar.module.css
Reverts laurenx122/marea-furwell#22
> Revert "Origin/admin profile page"

- src/components/Navbar/Navbar.js
GUYS NAA KOY NA WRONG SO SORRY
> BUG FIX HUHUHUHU

- src/pages/Home/Home.js
- src/pages/Signup/ClinicSubscribe.css
> gamayng edit

- src/components/Navbar/Navbar.js
- src/components/Navbar/Navbar.module.css
+ Added Personal Info Navbar
+ Info Modal
> NavBar Personal Information Modal

- src/components/Navbar/Navbar.js
- src/components/Navbar/Navbar.module.css
Di diay profile page huhuhu, Profile Information Modal
+ Update Personal Information
- Firstname, Last Name, Contact #
- Added Modals for Confirmation
- Confirm save info, Sign Out Confirmation
Bugs (need help if possible):
+ Buttons don't go center...
+ You can scroll on homepage as PetOwner while Modal is Active -> Can do myself
+ Style looks wrong lol
> Update Information Modal

- src/pages/Signup/ClinicSubscribe.js
-  Connected the Information in registering to firebase Note: if the clincs sign up they will automatically can log in,, so the approval by the admin is not yet implemented, ongoing...
> Clinic RrgistrationConnect to Firebase

- src/pages/Admin/AdminHome.css
- src/pages/Admin/AdminHome.js
- src/pages/Admin/AdminSubscription.js
- i fetch the data from the clinics registers that needs approval from the admin
- the data is already dynamic.
> AdminSubscription

- src/pages/PetOwner/PetOwnerHome.css
- src/pages/PetOwner/PetOwnerHome.js
+ Pets can now be added for PetOwners!
- Pets are hyperlinked, click for pet information
- Add new pets!
Info:
I used reference to get the logged in user for adding a new pet, so it shouldn't show the same pet for other userTypes
> Add Pet Details

- src/pages/Admin/AdminSubscription.css
- src/pages/Admin/AdminSubscription.js
- can confirm subscription
- can delete subscription
- can unsubscribe
- search feature
- confirmatio&success modals implemented
> ClinicSubscription Approval DB

- src/App.js
- src/pages/Home/ClinicLocator.css
- src/pages/Home/ClinicLocator.js
- src/pages/Home/Home.css
- src/pages/Home/Home.js
- locate me
- route for clinic locator
> Clinic Locator

- src/pages/Login/Login.js
- src/pages/PetOwner/PetOwnerHome.js
+ Added Book An Appointment
- Added a folder in firebase (appointments that tracks owner, pets, clinics)
REquired sa pet owner:
Pet Medical Records (needs veterinary)
> Book Appointments Added

- src/App.js
- src/pages/Login/Login.js
- src/pages/Maps/Maps.js
- src/pages/Veterinary/VeterinaryHome.css
- src/pages/Veterinary/VeterinaryHome.js
+ Added Veterinarian UI How to access?
Login -> Go to Vet Home
- INFO INSIDE PAGE NOT COMPLETE (REQUIRES COMPLETE INFO, NEED HELP)
+ Added contact info for Maps Page (While in Maps Page, Clicking "COntact Us" redirects users to bottom-most part of screen)
> VeterinarianHome, Maps Footer

- src/components/Navbar/Navbar.js
- src/components/Navbar/Navbar.module.css
- src/pages/Signup/Signup.css
- src/pages/Signup/Signup.js
+ Added Profile Pictures to Users
- Pet Owners
- Admin (im pretty sure)
+ Display Profile Picture in Navbar (if logged in)
How?
Cloudinary (thanks ange!!) <3
- Profile pages should contain pictures of users ( if uploaded in signup)
> Profile Picture Add-on

- src/components/Navbar/Navbar.js
- src/components/Navbar/Navbar.module.css
- src/pages/Login/Login.css
- src/pages/Login/Login.js
> login modal

- package-lock.json
- package.json
- src/App.js
- src/pages/Clinic/ClinicHome.css
- src/pages/Clinic/ClinicHome.js
- src/pages/Login/Login.js
- src/pages/Veterinary/VeterinaryHome.css
- src/pages/Veterinary/VeterinaryHome.js
+ Added Veterinarian to users
+ Currently Added a Clinic user from users (lux@gmail.com)
Edits:
ClinicHome:
- Changed Layout (Removed Navbar using App.js)
- Added functionality to add veterinarian (Requires further information)
NOTE: DO NOT ADD OR UPDATE CLINIC INFORMATION YET (IMAGES, STREET ADDRESS WTVR)
Login:
- Added redirection to VeterinaryHome
+ Installed npm install yocto-queue
> ClinicHome - Add Veterinary

- src/App.js
- src/pages/Clinic/ClinicHome.css
- src/pages/Clinic/ClinicHome.js
- src/pages/PetOwner/PetOwnerHome.css
+ Authenticates added veterinarian removed
+ Now properly adds veterinary
+ Updated PetOwner css file
+ Removed Navbar in ClinicHome
Bug:
- need to adjust photo of Clinic when logged in (SAKTO NANG CSS)
STILL DONT EDIT IMAGE OF CLINIC PLEASE OR ADD ANY INFO IN CLINIC EDIT
> Bugfixes to ClinicHome.js, Updated PetOwnerHome.css

- src/pages/Clinic/ClinicHome.css
- src/pages/Clinic/ClinicHome.js
profile 150px on clinic-image-container and clinic-profile-image
> fixed clinic Profile

- src/components/Navbar/Navbar.js
- src/components/Navbar/Navbar.module.css
- src/pages/Signup/Signup.css
- src/pages/Signup/Signup.js
> modal signup

- src/components/Navbar/Navbar.js
- src/pages/Login/Login.css
- src/pages/Login/Login.js
- src/pages/Signup/Signup.css
- src/pages/Signup/Signup.js
> fix modals final

- src/firebase.js
- src/pages/Admin/AdminSubscription.js
- src/pages/Signup/ClinicSubscribe.js
- still not working ang alert sa pending account
> fix subscription&unsubscribe/clinicSignup

- package-lock.json
- package.json
- src/pages/Admin/AdminSubscription.js
Admin can email clinics for approval of subscription
> email-adminsub

- src/components/Navbar/Navbar.js
- src/pages/Clinic/ClinicHome.css
- src/pages/FindClinic/FindClinic.css
- src/pages/PetOwner/PetOwnerHome.css
- src/pages/PetOwner/PetOwnerHome.js
- src/pages/Signup/ClinicSubscribe.css
- src/pages/Veterinary/VeterinaryHome.css
+ Pet Owner Adjusted Editting Details now properly displays information
- Book Appointment moved to home.js
> Navbar Adjustment, PetOwner Edit, Styling Change for ClinicSubscribe.css

- src/pages/Signup/Signup.css
- src/pages/Signup/Signup.js
+ Added OTP after signing up to reduce spam
- Users must register with PROPER Email (Emailing Service max is 200) right now its 16/200 Don't spam sign up!!
> Signup OTP

- src/App.js
- src/pages/ClinicDetails/ClinicDetails.js
- src/pages/PetOwner/PetOwnerHome.css
- src/pages/Veterinary/VeterinaryHome.css
- src/pages/Veterinary/VeterinaryHome.js
+ Added Veterinarian UI
- Upcoming Appointments
- Schedule of Veterinarian
+ Removed Navbar in Veterinarian UI
> Veterinarian UI, style changes

- src/components/Navbar/Navbar.module.css
- src/pages/Clinic/ClinicHome.css
- src/pages/Clinic/ClinicHome.js
- src/pages/PetOwner/PetOwnerHome.js
- src/pages/Veterinary/VeterinaryHome.css
- src/pages/Veterinary/VeterinaryHome.js
+ Clinic Home Patient will be highlighted and upon click will provide pet details
+ Adjusted Veterinary Home
+ Adjusted Scroll Bar Progress to not block modals
> Clinic Home Pet Details

- package-lock.json
- package.json
- src/pages/Veterinary/VeterinaryHome.css
- src/pages/Veterinary/VeterinaryHome.js
+ Added Syncfusion API to integrate Schedule of Appointments and Veterinarian Schedule
- API is limited to 1 month (until April 22)
+ View appointment details by clicking them..
Bugs:
+ Pet Age doesn't work..
> Veterinary Appointments + Schedule

- package-lock.json
- package.json
- src/pages/Clinic/ClinicHome.css
- src/pages/Clinic/ClinicHome.js
- src/pages/Veterinary/VeterinaryHome.js
+ Updated Appoinntments to be using Calendar API
+ Past Appointments will be in "Records"
+ renamed css to be unique to clinichome (added -c)
> ClinicHome Appointments Adjustment

- src/pages/Veterinary/VeterinaryHome.css
- src/pages/Veterinary/VeterinaryHome.js
+ Added Veterinarian Health Records
+ Fixed Pet Age Issue for Appointment Details
> Veterinarian Health Records

- src/pages/ClinicDetails/ClinicDetails.css
- src/pages/ClinicDetails/ClinicDetails.js
+ Map for the selected clinic
+ Google street view for the clinic map selected
+ email hover for full text and not truncated
+ fetched phone number
> Clinic Details Maps

- src/pages/ClinicDetails/ClinicDetails.css
- src/pages/PetOwner/PetOwnerHome.css
- src/pages/PetOwner/PetOwnerHome.js
- src/pages/Signup/ClinicSubscribe.js
- Added search Bar in heath records in pet owner and add a clinics para dali makit an
- Clinic Description css
> I tried Pero D jud siya(ClinicSubscribe Alert)

- package-lock.json
- package.json
- src/pages/Clinic/ClinicHome.css
- src/pages/Clinic/ClinicHome.js
> Analytics-Clinic

- package-lock.json
- package.json
- src/pages/ClinicDetails/ClinicDetails.js
- src/pages/PetOwner/PetOwnerHome.js
- src/pages/Veterinary/VeterinaryHome.js
- i already edit the code setting a status in firestore in accepting the appointments from petowner to vet.
- the fetching logic is also okay.
> AcceptingAppointmentStatus

- src/pages/PetOwner/PetOwnerHome.css
- src/pages/PetOwner/PetOwnerHome.js
+ UI for calendar
+ starts at Sunday for the week in the calendar
> Reschedule Calendar UI

- package-lock.json
- src/pages/Clinic/ClinicHome.js
gender count analytics + deleted not used lines
> gender distribution

- package-lock.json
- package.json
- src/pages/Clinic/ClinicHome.js
fixed analytics (age, pet type, gender)
> fixed analytics

- package-lock.json
- src/pages/Veterinary/VeterinaryHome.js
Veterinary Home Can now Complete Appointments & Displays in Health Records
> Completing Appointments

- src/pages/ClinicDetails/ClinicDetails.js
- src/pages/Veterinary/VeterinaryHome.js
Vet now only checks in Appoinntments for Status changing, checks pending Appointments and accepts appointments...
ClinicDetails now Appends/Pushes directly to 'appointments' folder when petOwner books an appointment
> Appointment Status Checking

- package-lock.json
- src/pages/ClinicDetails/ClinicDetails.css
- src/pages/ClinicDetails/ClinicDetails.js
+ Booking Appointment now lets me choose the day of the appointment then the time of the appointment based on the veterinarian's schedule..
+ Integration of react-calendar for ClinicDetails..
+ Versatility of Schedule now applies, when booking, appointments that are scheduled do not reflect when booking appointment, fully booked days will be red
> Booking Appointment

- src/pages/ClinicDetails/ClinicDetails.css
+ Map doesn't overlap Navbar anymore for ClinicDetails map
> Map for ClinicDetails

- src/pages/PetOwner/PetOwnerHome.css
- src/pages/PetOwner/PetOwnerHome.js
+ Pet Type and Pet Breed now drop down box
+ Added "Others" as a choice for uncommon Pet Types/Breeds
> Pet Type, Pet Breed Dropdown Box

- src/pages/Admin/AdminAnalytics.js
- src/pages/Clinic/ClinicHome.js
> analytics from clinic moved to admin

- src/pages/Admin/AdminAnalytics.js
> updated adminAnalytics

- src/pages/PetOwner/PetOwnerHome.js
- src/pages/Signup/Signup.js
+ Emailing Logged in users when appointment is tomorrow/today
Bugs:
Email sending is twice rather than 1 time only
> Email Day Before/On The Day Appointments

- src/pages/PetOwner/PetOwnerHome.css
- src/pages/PetOwner/PetOwnerHome.js
Before and On the Day Appointment Notification
> Before and On the Day Appointment Notification

- src/pages/PetOwner/PetOwnerHome.css
- src/pages/PetOwner/PetOwnerHome.js
Before and On the Day Appointment Notification
> Revert "Before and On the Day Appointment Notification"

- package-lock.json
- package.json
- src/pages/Clinic/ClinicHome.css
- src/pages/Clinic/ClinicHome.js
feat: add search functionality for patients and enhance modal styling
> clinic home design 2

- src/components/Navbar/Navbar.js
- src/components/Navbar/Navbar.module.css
+ Responsive Nav bar for Tablets and Mobile Phones
- Bugs:
-  PetOwner Home is bugges with navbar
> Navigation Bar Responsive

- src/pages/Veterinary/VeterinaryHome.js
> fix: vet sync and reload

- package-lock.json
- src/pages/Veterinary/VeterinaryHome.css
- src/pages/Veterinary/VeterinaryHome.js
Veterinarian Completed Will only update status of Appointment to "Completed" rather than pushing details to "pastAppointments" folder
+ Update to Sidebar UI
> Veterinarian Complete & Sidebar

- src/App.js
- src/pages/PetOwner/PetOwnerHome.css
- src/pages/PetOwner/PetOwnerHome.js
Navbar removed and Signout Btn displayed in sidebar
> Navbar and Signout Btn

- src/pages/Clinic/ClinicHome.css
- src/pages/Clinic/ClinicHome.js
+ Clinic Emailing When Accepting Appointments to users
> Clinic Emailing Accepted Appointments

- src/components/Footer/Mobile_Footer.js
- src/components/Navbar/Navbar.js
- src/pages/PetOwner/PetOwnerHome.js
- src/pages/Veterinary/VeterinaryHome.css
- src/pages/Veterinary/VeterinaryHome.js
+ Veterinarian Responsive is now available
+ Navbar Changes in Mobile Mode (Go back to Dashboard for PetOwner, Clinic, VeterinaryHome) if go to home
+ Added a Search Bar for Veterinarian
+ Removed + (For booking) in footer of veterinary
+ Made sure dashboard goes back to "Upcoming Appointments" for Veterinary / "Pet Details" for Pet Owner
> Veterinary Responsive, Navbar Changes

- src/pages/Clinic/ClinicHome.css
- src/pages/Clinic/ClinicHome.js
> vetSched and vetStatus

- src/pages/Services/Services.css
- src/pages/Services/Services.js
> mobile responsive

- src/App.js
- src/components/Navbar/Navbar.js
- src/pages/ClinicDetails/ClinicDetails.css
- src/pages/ClinicDetails/ClinicDetails.js
- src/pages/FindClinic/FindClinic.css
- src/pages/FindClinic/FindClinic.js
+ FindClinic, ClinicDetails are now Responsive
+ Made sure Clinics now redirect to "/ClinicDetails" rather than showing clinicId for url
+ Navbar can now have user profile when in ClinicDetails and FindClinic (Redirects back to user type dashboard)
+ Added back "Back to Clinics" button in ClinicDetails
> FindClinic, ClinicDetails Responsive

- src/pages/PetOwner/PetOwnerHome.css
- src/pages/PetOwner/PetOwnerHome.js
Responsive all panels, with profile modal, sidebar, and footer.
> Pet Owner Responsive

- src/components/Footer/Mobile_Footer.css
- src/pages/PetOwner/PetOwnerHome.css
- src/pages/PetOwner/PetOwnerHome.js
- src/pages/Veterinary/VeterinaryHome.css
fixed error in pet owner edit profile
> Edit Profile in Pet Owner Fixed Error

- src/components/Footer/Mobile_Footer.js
- src/pages/ClinicDetails/ClinicDetails.js
- src/pages/FindClinic/FindClinic.js
- src/pages/PetOwner/PetOwnerHome.css
- src/pages/PetOwner/PetOwnerHome.js
- src/pages/Veterinary/VeterinaryHome.css
- src/pages/Veterinary/VeterinaryHome.js
+VeterinaryHome Responsiveness changes
+Mobile Footer Changes for
FindClinic & ClinicDetails (now you can return to dashboard if booking)
+Removed Emailing Service in PetOwnerHome
+Slight Css changes to petowner
> VeterinaryHome, FindClinic,ClinicDetails

- src/pages/ClinicDetails/ClinicDetails.js
- src/pages/PetOwner/PetOwnerHome.js
- src/pages/Veterinary/VeterinaryHome.js
+ Veterinarian can Add Diagnosis & Treatment for the Completed Appointments
+ PetOwner can retrieve these data
+ Notes is back for Pet, Vets, and In Clinic Details
> Vet/Pet Diagnosis and Treatment

- src/components/Navbar/Navbar.module.css
- src/pages/Signup/ClinicSubscribe.css
+ Clinic Subscribe Adjusted for Responsiveness
+ Navbar Updated Height size
> ClinicSubscribe & Navbar Responsive

- src/pages/Veterinary/VeterinaryHome.css
- src/pages/Veterinary/VeterinaryHome.js
+ Responsive Profile Modal now fits
Image + Full Name format
< - Sign out
> Veterinary Profile Modal Adjustment

- src/pages/Clinic/ClinicHome.css
- src/pages/Clinic/ClinicHome.js
+ no dupe in select day
+ by hour,  always "00" in minutes but when clicked, it is scrollable but still minutes is "00" so it's still fine
> Edit Vet Sched

- src/pages/Clinic/ClinicHome.js
- src/pages/PetOwner/PetOwnerHome.js
used only 2 templates for sending 5 types of email (Accepted, Declined, Cancelled, Rescheduled, and The Day of Appointment)
> send email reminder

- src/pages/Veterinary/VeterinaryHome.js
+ now displays proper diagnosis and treatment
> Veterinary Health Records

- src/pages/Clinic/ClinicHome.css
- src/pages/PetOwner/PetOwnerHome.css
- src/pages/Veterinary/VeterinaryHome.css
Fixed Add pet fields width, signout buttons width, and vet profile edit justified
> CSS Update

- src/components/Footer/Mobile_Footer.css
- src/components/Navbar/Navbar.module.css
- src/pages/Clinic/ClinicHome.css
- src/pages/Clinic/ClinicHome.js
- src/pages/PetOwner/PetOwnerHome.css
- src/pages/PetOwner/PetOwnerHome.js
- src/pages/Signup/Signup.js
- src/pages/Veterinary/VeterinaryHome.css
- src/pages/Veterinary/VeterinaryHome.js
+ Navbar now 60%
+ OTP ClickAway is Okay
+ SignOutSuccessful okay on localhost at first
- Will Recheck Success Modal
> Navbar, OTP Clickout, SignOutSuccessful

- src/components/Footer/Mobile_Footer.css
- src/components/Footer/Mobile_Footer.js
+changed color
+adjusted home mobile footer
> Responsive Home Mobile Footer
